# Numpy Basics

Welcome to section of Numpy and Pandas. This is the most used Python libraries for data science. NumPy consists of a powerful data structure called multidimensional arrays. Pandas is another powerful Python library that provides fast and easy data analysis platform.

NumPy is a library written for scientific computing and data analysis. It stands for numerical python and also known as array oriented computing.

The most basic object in NumPy is the ndarray, or simply an array which is an n-dimensional, homogeneous array. By homogenous, we mean that all the elements in a NumPy array have to be of the same data type, which is commonly numeric (float or integer).


 # Why Numpy?
 
 ===>> convenience & speed
 
 ===>> Numpy is much faster than the standard python ways to do computations.
 
 ===>> Vectorised code typically does not contain explicit looping and indexing etc. (all of this happens behind the scenes, in precompiled C-code), and thus it is much more concise.

 ===>> Also, many Numpy operations are implemented in C which is basically being executed behind the scenes, avoiding the general cost of loops in Python, pointer indirection and per-element dynamic type checking. The speed boost depends on which operations you're performing.
 
 ==>> NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists

In [12]:
# numpy lib ---->> import numpy ---> we have api --> numpy.api()
# list with 10  elements
import numpy
a = [12,90.2]# hetro
arr = numpy.array([12,90.2])# homo
print "ndim : ",arr.ndim
print "shape : ",arr.shape
print "list a : ",a
print "array arr : ",arr
print "size of a : ",a.__sizeof__()
print "size of arr: ",arr.__sizeof__()


ndim :  1
shape :  (2L,)
list a :  [12, 90.2]
array arr :  [12.  90.2]
size of a :  56
size of arr:  112


In [8]:
# for addition of corresponding elements in lists we are used loops and indexing
a = [1,8,9]
b = [3,2,9]
#c = [4,10,18]
c =[]
if(len(a) == len(b)):
    for i in range(len(a)):
        c.append(a[i]+b[i])
print c

[4, 10, 18]


In [13]:
# for addition of corresponding elements in numpy array we avoid the  loops and indexing
import numpy
a = numpy.array([[1,8,9]])
b = numpy.array([[3,2,9]])
print a.ndim
print b.ndim
print a.shape
print b.shape
if(a.shape == b.shape):
    c = a+b
    print c

2
2
(1L, 3L)
(1L, 3L)
[[ 4 10 18]]


In [15]:
import numpy
a = numpy.array([[1,8,9],[8,3,4]])
b = numpy.array([[[1,8,9],[8,3,4]]])
print a.ndim
print b.ndim
print a.shape
print b.shape
print a
print b



2
3
(2L, 3L)
(1L, 2L, 3L)
[[1 8 9]
 [8 3 4]]
[[[1 8 9]
  [8 3 4]]]


In [16]:
l1 = [1,2,3]
l2 = [4,5,6]
c =[]
c = [l1[i]+l2[i] for i in range(len(l1)) ] # list compreshasation
c

[5, 7, 9]

In [1]:
import numpy
a = numpy.array([1,2])
b = numpy.array([[4,5,6]])
print a
print b
print a.shape
print b.shape
print a.ndim
print b.ndim
print a.__sizeof__()
print b.__sizeof__()

[1 2]
[[4 5 6]]
(2L,)
(1L, 3L)
1
2
104
124


In [3]:
import numpy
a = numpy.array([[1,2,3.0],[4,5,6]]) # (2L , 3L)
print a.ndim
print a.shape
print a.__sizeof__()
print a

2
(2L, 3L)
160
[[1. 2. 3.]
 [4. 5. 6.]]


In [9]:
#  1D , 2 D , 3D      ---> type of array elements
import numpy as np
a = np.array([1,2.2,3] , dtype = int) # 1 D  ---> 3L
b = np.array([[1,2,3],[4,5,6],[7,8,9]] , dtype =float) # 2 D ---> 3*3
c = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[9,8,0],[6,9,1],[3,8,1]]])
print a
print a.shape
print a.ndim
print a.__sizeof__()
print a.dtype
print type(a)
print"****************"
print b
print b.shape
print b.ndim
print b.__sizeof__()
print b.dtype
print type(a)
print"****************"
print c
print c.shape
print c.ndim
print c.__sizeof__()
print c.dtype
print type(a)
print"****************"

[1 2 3]
(3L,)
1
108
int32
<type 'numpy.ndarray'>
****************
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
(3L, 3L)
2
184
float64
<type 'numpy.ndarray'>
****************
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 0]
  [6 9 1]
  [3 8 1]]]
(2L, 3L, 3L)
3
200
int32
<type 'numpy.ndarray'>
****************


In [15]:
import numpy as np
print np.arange(10)
print np.arange(10).shape
print range(10)  # list   
print np.arange(12,21)
print range(12,21)
print np.arange(10,100,20)
print range(10,100,20)

[0 1 2 3 4 5 6 7 8 9]
(10L,)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[12 13 14 15 16 17 18 19 20]
[12, 13, 14, 15, 16, 17, 18, 19, 20]
[10 30 50 70 90]
[10, 30, 50, 70, 90]


In [13]:
import numpy
help(numpy.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

# Performance measurement
I mentioned that the key advantages of numpy are convenience and speed of computation.

You'll often work with extremely large datasets, and thus it is important point for you to understand how much computation time (and memory) you can save using numpy, compared to standard python lists.

In [16]:
c=range(3) # [0,1,2] ---> [0,1,8]
l =[i**3  for i  in c]
l

[0, 1, 8]

In [17]:
import numpy as np
c = np.arange(3) # [0,1,2]
d =c**3
print d

[0 1 8]


In [19]:
c = range(100000)  # [0,1,2,3,4---------99999] ---> [0,1,8,27,64----]
%timeit[i**3 for i in c]
c = range(100000)  # [0,1,2,3,4---------99999] ---> [0,1,8,27,64----]
b = [i**3 for i in c]

1 loop, best of 3: 198 ms per loop


In [20]:
import numpy as np
c = np.arange(100000)
%timeit c**3
c = np.arange(100000)
b = c**3

1000 loops, best of 3: 394 µs per loop


Still not convinced? want to see one more intresting example

In [21]:
l1=[1,2,3]
l2 =[4,5,6]
print [l1[i]*l2[i] for i in range(len(l1))]

[4, 10, 18]


In [22]:
fun = lambda x : x*2
fun(89)

178

In [23]:
%timeit list(map(lambda x, y: x*y, l1, l2))
print list(map(lambda x, y: x*y, l1, l2))

100000 loops, best of 3: 2.25 µs per loop
[4, 10, 18]


In [25]:
import numpy as np
l1 = [1,2,3]
l2 = [4,5,6]
a1 = np.array(l1)
b1 = np.array(l2)
print a1 * b1
print a1
print b1

[ 4 10 18]
[1 2 3]
[4 5 6]


so I can do everything without even writing a loop? yes... ohh wao

# Creating Numpy array

There are multiple ways to create numpy array. Lets walk over them

In [26]:
import numpy as np

In [27]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [29]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.ones((4,3),int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [31]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [32]:
np.full((5,4),9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [33]:
np.full((7,6),8.9,dtype=int)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [34]:
np.diag([7,9,8,1,6,8,5])

array([[7, 0, 0, 0, 0, 0, 0],
       [0, 9, 0, 0, 0, 0, 0],
       [0, 0, 8, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 5]])

In [35]:
v = np.array([1,2])
a =np.tile(v,(4,5)) # stack 4*5 copies of v on top of each other
print(a)
print(a.ndim)
print(a.shape)

[[1 2 1 2 1 2 1 2 1 2]
 [1 2 1 2 1 2 1 2 1 2]
 [1 2 1 2 1 2 1 2 1 2]
 [1 2 1 2 1 2 1 2 1 2]]
2
(4L, 10L)


In [36]:

# between 0 and 1
np.random.random()

0.04018362157397404

In [37]:
# so let say I want a random value between 0and 50
50*np.random.random()

16.907802858510813

In [38]:
# so let say I want a random value between 10and 50
10+ 40*np.random.random()

42.10899396574093

In [39]:
np.random.random([3,3])

array([[0.12134685, 0.21562155, 0.75227312],
       [0.85148308, 0.01789486, 0.34606673],
       [0.59829873, 0.04079237, 0.11344027]])

In [40]:
import numpy as np
# 100 values between 1 and 50
a = np.linspace(1,50,100)
a
print(len(a))
print(a)

100
[ 1.          1.49494949  1.98989899  2.48484848  2.97979798  3.47474747
  3.96969697  4.46464646  4.95959596  5.45454545  5.94949495  6.44444444
  6.93939394  7.43434343  7.92929293  8.42424242  8.91919192  9.41414141
  9.90909091 10.4040404  10.8989899  11.39393939 11.88888889 12.38383838
 12.87878788 13.37373737 13.86868687 14.36363636 14.85858586 15.35353535
 15.84848485 16.34343434 16.83838384 17.33333333 17.82828283 18.32323232
 18.81818182 19.31313131 19.80808081 20.3030303  20.7979798  21.29292929
 21.78787879 22.28282828 22.77777778 23.27272727 23.76767677 24.26262626
 24.75757576 25.25252525 25.74747475 26.24242424 26.73737374 27.23232323
 27.72727273 28.22222222 28.71717172 29.21212121 29.70707071 30.2020202
 30.6969697  31.19191919 31.68686869 32.18181818 32.67676768 33.17171717
 33.66666667 34.16161616 34.65656566 35.15151515 35.64646465 36.14141414
 36.63636364 37.13131313 37.62626263 38.12121212 38.61616162 39.11111111
 39.60606061 40.1010101  40.5959596  41.09090909

In [41]:
len(a)

100

In [42]:
#memory used by each array element in bytes
a.itemsize
#a.shape


8

In [43]:
np.arange(24).reshape(6,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [44]:
# -1 will automatically adjust dimention
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

# accessing Numpy array element

In [45]:
a = np.array([2,4,6,8,10,12,14,16])


In [46]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [47]:
a[2]


6

In [48]:
a[[2,4]]

array([ 6, 10])

In [49]:
a[2:]

array([ 6,  8, 10, 12, 14, 16])

In [50]:
a[2:5]

array([ 6,  8, 10])

In [51]:
a[1::2]

array([ 4,  8, 12, 16])

Lets check the same for 2 D array

In [52]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [53]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
a[2,2]

9

In [55]:
a > 2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [56]:
a[a > 2]

array([3, 4, 5, 6, 7, 8, 9])

In [57]:
a[(a > 2) & (a < 5)]

array([3, 4])

In [58]:
b = a

In [59]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
b[0] = 11

In [61]:
b

array([[11, 11, 11],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [62]:
# Notice a is also changed
a

array([[11, 11, 11],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [63]:
np.shares_memory(a,b)

True

In [64]:
a = np.arange(10)

In [65]:
b = a.copy()

In [66]:
b[0] = 11

In [67]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [68]:
np.shares_memory(a,b)

False

In [69]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# More operations

In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])

In [3]:
print a
print a.shape
print a.ndim


[[1 2 3]
 [4 5 6]]
(2L, 3L)
2


In [4]:
# matrix transpose
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
b = np.array([[7,8,9],[10,5,12]])

In [6]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b


array([[ 7,  8,  9],
       [10,  5, 12]])

In [8]:
print a == b
print a < b
print a > b
print a != b
print a <= b
print a >= b

[[False False False]
 [False  True False]]
[[ True  True  True]
 [ True False  True]]
[[False False False]
 [False False False]]
[[ True  True  True]
 [ True False  True]]
[[ True  True  True]
 [ True  True  True]]
[[False False False]
 [False  True False]]


In [9]:
print a
print b

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10  5 12]]


In [10]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  5, 12]])

In [11]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10,  5, 12]])

# MAthmatical operation

In [13]:
a = np.arange(1,10)
print a

[1 2 3 4 5 6 7 8 9]


In [14]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [15]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [16]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [17]:
np.sum(a)

45

In [18]:
a.mean()

5.0

In [22]:
a = np.arange(1,10)

print np.median(a)
a = np.arange(1,11)
print np.median(a)

5.0
5.5


In [23]:
a.std()

2.8722813232690143

In [29]:
a = np.arange(1,10).reshape(3,3)
print a
a = np.arange(1,10).reshape(3,-1)
print a


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
b = np.array([[1,3],[4,5]])
np.linalg.det(b)

-6.999999999999999

In [31]:
np.linalg.det(a)

-9.51619735392994e-16

In [32]:
np.linalg.det(a)
#help(np.linalg.det)

-9.51619735392994e-16

In [33]:
print(np.linalg.inv(a))
#help(np.linalg.inv)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [34]:
np.linalg.eig(a)
#help(np.linalg.eig)

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [35]:
print a

b = a.T
print b

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [36]:
np.dot(a,b)


array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [37]:
a = np.array([1,1,0], dtype = bool)
b = np.array([1,0,1], dtype = bool)


In [38]:
np.logical_or(a,b)

array([ True,  True,  True])

In [39]:
np.logical_and(a,b)

array([ True, False, False])

In [40]:
print np.logical_not(a)
print np.logical_xor(a,b)

[False False  True]
[False  True  True]


In [41]:
np.all(a == b)

False

In [42]:
a = np.array([[1,2],[3,4]])

In [43]:
a


array([[1, 2],
       [3, 4]])

In [44]:
a.sum()

10

In [45]:
a.sum(axis=0)

array([4, 6])

In [46]:
a.sum(axis=1)

array([3, 7])

In [47]:
a.max()

4

In [48]:
a.argmax()

3

In [49]:
a=np.array([[1,5,2],[3,1,8]])

In [51]:
print a.shape
print a.ndim

(2L, 3L)
2


In [52]:
a = a[:,np.newaxis] # adds a new axis -> 2D
print a
print a.shape
print a.ndim

[[[1 5 2]]

 [[3 1 8]]]
(2L, 1L, 3L)
3


In [53]:
a

array([[[1, 5, 2]],

       [[3, 1, 8]]])

In [54]:
a = a[:,np.newaxis] # adds a new axis -> 2D
print a
print a.shape
print a.ndim

[[[[1 5 2]]]


 [[[3 1 8]]]]
(2L, 1L, 1L, 3L)
4


In [55]:
np.sort(a)

array([[[[1, 2, 5]]],


       [[[1, 3, 8]]]])

In [56]:
np.argsort(a)
#help(np.argsort)

array([[[[0, 2, 1]]],


       [[[1, 0, 2]]]], dtype=int64)

In [57]:
np.argsort(a)

array([[[[0, 2, 1]]],


       [[[1, 0, 2]]]], dtype=int64)

In [58]:
np.sort(a)

array([[[[1, 2, 5]]],


       [[[1, 3, 8]]]])

In [59]:
a

array([[[[1, 5, 2]]],


       [[[3, 1, 8]]]])

In [60]:
a=np.array([[11,12,14],[9,10,12],[34,45,0]])

In [61]:
a.argmin()

8